# Generated by Django 5.0 on 2023-12-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_user_main', '0002_users_remove_vehicle_username_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='truck_num',
            field=models.IntegerField(default='SOME STRING'),
        ),
    ]
