# Generated by Django 5.0 on 2023-12-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_user_main', '0003_alter_vehicle_truck_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='truck_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_user_main.users'),
        ),
    ]
